title: sunho lee. 
description: Hi, I prefer sunho.
#permalink: ':title/'
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: sunho # add your name
author-img: sunny-ciceron.jpeg # add your photo
about-author: I am a web developer focusing on back-end development. Always hungry to keep learning. # add description
social-twitter: sssunho# add your Twitter handle
social-facebook: sunho.lee.58511 # add your Facebook handle
social-github: sssunho # add your Github handle
social-linkedin: sunho-lee # add your Linkedin handle
social-email: sssunho.lee@gmail.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - gemoji

paginate: 100
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
